apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: nginx-project
  source:
    repoURL: https://github.com/hetgajera01/argocd.git    # Replace it with your forked repo
    targetRevision: main
    path: nginx/
  destination:
    server: https://172.31.31.75:33893     # Replace with your Cluster Url, To get run: `argocd cluster list`
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:                 # Additional sync options
      - CreateNamespace=true      # Auto-create namespace if it doesn't exist
