apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache             # Child app name
  namespace: argocd
  annotations:
    # The email notifier must be configured in argocd-notifications-cm.yaml, The `.email` is the name of the notifier, i.e, `service.email` in the argocd-notifications-cm.yaml.
    # Subscribe to notifications when the app health is degraded.
    notifications.argoproj.io/subscribe.on-health-degraded.email: "hetgajera01@gmail.com"  # you can add multiple email ids separated by comma like "<receiver@example.com>, <receiver2@example.com>"
    # Subscribe to notifications when the app is successfully deployed.
    notifications.argoproj.io/subscribe.on-deployed.email: "hetgajera01@gmail.com" # you can add multiple email ids separated by comma like "<receiver@example.com>, <receiver2@example.com>"
spec:
  project: default
  source:
    repoURL: https://github.com/hetgajera01/argocd.git # Repo containing child apps(that you have forked and cloned earlier)
    targetRevision: main
    path: apache/    # path of Apache app in `argocd-demos` repo
  destination:
    server: https://172.31.31.75:33893 # Replace with your Cluster Url, To get run: `argocd cluster list`
    namespace: apache
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
